--
-- PostgreSQL database dump
--

\restrict 2WPWajyQyYcD4VajFESe03TbLodHGfLMwoshF7qboBWQnFL0ts3QLKkAcjDTwUB

-- Dumped from database version 14.23 (Ubuntu 14.23-1.pgdg22.04+1)
-- Dumped by pg_dump version 14.23 (Ubuntu 14.23-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'SQL_ASCII';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: api_tokens; Type: TABLE; Schema: public; Owner: darkai
--

CREATE TABLE public.api_tokens (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    token text NOT NULL,
    name text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_used timestamp with time zone,
    revoked boolean DEFAULT false NOT NULL
);


ALTER TABLE public.api_tokens OWNER TO darkai;

--
-- Name: api_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: darkai
--

CREATE SEQUENCE public.api_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.api_tokens_id_seq OWNER TO darkai;

--
-- Name: api_tokens_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: darkai
--

ALTER SEQUENCE public.api_tokens_id_seq OWNED BY public.api_tokens.id;


--
-- Name: containers; Type: TABLE; Schema: public; Owner: darkai
--

CREATE TABLE public.containers (
    user_id bigint NOT NULL,
    host_id bigint NOT NULL,
    container_name text NOT NULL,
    port integer NOT NULL,
    status text DEFAULT 'stopped'::text NOT NULL,
    last_active timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    browser_port integer
);


ALTER TABLE public.containers OWNER TO darkai;

--
-- Name: goose_db_version; Type: TABLE; Schema: public; Owner: darkai
--

CREATE TABLE public.goose_db_version (
    id integer NOT NULL,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.goose_db_version OWNER TO darkai;

--
-- Name: goose_db_version_id_seq; Type: SEQUENCE; Schema: public; Owner: darkai
--

ALTER TABLE public.goose_db_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goose_db_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hosts; Type: TABLE; Schema: public; Owner: darkai
--

CREATE TABLE public.hosts (
    id bigint NOT NULL,
    name text NOT NULL,
    control_url text NOT NULL,
    internal_ip text NOT NULL,
    capacity integer DEFAULT 50 NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.hosts OWNER TO darkai;

--
-- Name: hosts_id_seq; Type: SEQUENCE; Schema: public; Owner: darkai
--

CREATE SEQUENCE public.hosts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.hosts_id_seq OWNER TO darkai;

--
-- Name: hosts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: darkai
--

ALTER SEQUENCE public.hosts_id_seq OWNED BY public.hosts.id;


--
-- Name: oauth_identities; Type: TABLE; Schema: public; Owner: darkai
--

CREATE TABLE public.oauth_identities (
    provider text NOT NULL,
    provider_uid text NOT NULL,
    user_id bigint NOT NULL,
    email text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.oauth_identities OWNER TO darkai;

--
-- Name: oauth_state; Type: TABLE; Schema: public; Owner: darkai
--

CREATE TABLE public.oauth_state (
    state text NOT NULL,
    provider text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL
);


ALTER TABLE public.oauth_state OWNER TO darkai;

--
-- Name: payments; Type: TABLE; Schema: public; Owner: darkai
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    provider text NOT NULL,
    provider_pid text,
    kind text NOT NULL,
    tier text,
    period text,
    days integer DEFAULT 0 NOT NULL,
    budget_micros bigint DEFAULT 0 NOT NULL,
    price_usd_cents bigint DEFAULT 0 NOT NULL,
    pay_currency text,
    status text DEFAULT 'waiting'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    storage_bytes bigint DEFAULT 0 NOT NULL
);


ALTER TABLE public.payments OWNER TO darkai;

--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: darkai
--

CREATE SEQUENCE public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.payments_id_seq OWNER TO darkai;

--
-- Name: payments_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: darkai
--

ALTER SEQUENCE public.payments_id_seq OWNED BY public.payments.id;


--
-- Name: session_episodes; Type: TABLE; Schema: public; Owner: darkai
--

CREATE TABLE public.session_episodes (
    user_id bigint NOT NULL,
    session_id text NOT NULL,
    memory_id bigint,
    msg_count integer DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.session_episodes OWNER TO darkai;

--
-- Name: sessions; Type: TABLE; Schema: public; Owner: darkai
--

CREATE TABLE public.sessions (
    token text NOT NULL,
    user_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    last_seen timestamp with time zone DEFAULT now() NOT NULL,
    user_agent text,
    ip text
);


ALTER TABLE public.sessions OWNER TO darkai;

--
-- Name: tier_defaults; Type: TABLE; Schema: public; Owner: darkai
--

CREATE TABLE public.tier_defaults (
    tier text NOT NULL,
    budget_micros bigint NOT NULL,
    daily_limit_micros bigint DEFAULT 0 NOT NULL,
    storage_bytes bigint DEFAULT 1073741824 NOT NULL
);


ALTER TABLE public.tier_defaults OWNER TO darkai;

--
-- Name: totp_pending; Type: TABLE; Schema: public; Owner: darkai
--

CREATE TABLE public.totp_pending (
    token text NOT NULL,
    user_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    user_agent text,
    ip text
);


ALTER TABLE public.totp_pending OWNER TO darkai;

--
-- Name: usage_logs; Type: TABLE; Schema: public; Owner: darkai
--

CREATE TABLE public.usage_logs (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    specialty text NOT NULL,
    model text NOT NULL,
    input_tokens integer DEFAULT 0 NOT NULL,
    output_tokens integer DEFAULT 0 NOT NULL,
    cost_cents integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    cost_micros bigint DEFAULT 0 NOT NULL
);


ALTER TABLE public.usage_logs OWNER TO darkai;

--
-- Name: usage_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: darkai
--

CREATE SEQUENCE public.usage_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.usage_logs_id_seq OWNER TO darkai;

--
-- Name: usage_logs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: darkai
--

ALTER SEQUENCE public.usage_logs_id_seq OWNED BY public.usage_logs.id;


--
-- Name: user_memory; Type: TABLE; Schema: public; Owner: darkai
--

CREATE TABLE public.user_memory (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    mem_type text DEFAULT 'fact'::text NOT NULL,
    category text DEFAULT 'other'::text NOT NULL,
    content_enc bytea NOT NULL,
    content_nonce bytea NOT NULL,
    embedding public.vector(1536),
    confidence real DEFAULT 0.8 NOT NULL,
    source_session text,
    retrieval_count integer DEFAULT 0 NOT NULL,
    last_used_at timestamp with time zone,
    superseded_by bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.user_memory OWNER TO darkai;

--
-- Name: user_memory_id_seq; Type: SEQUENCE; Schema: public; Owner: darkai
--

CREATE SEQUENCE public.user_memory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.user_memory_id_seq OWNER TO darkai;

--
-- Name: user_memory_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: darkai
--

ALTER SEQUENCE public.user_memory_id_seq OWNED BY public.user_memory.id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: darkai
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    username text NOT NULL,
    email text,
    pass_hash text NOT NULL,
    tier text DEFAULT 'basic'::text NOT NULL,
    compute_budget_cents integer DEFAULT 1000 NOT NULL,
    compute_used_cents integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    api_token text,
    daily_used_cents integer DEFAULT 0 NOT NULL,
    daily_limit_cents integer DEFAULT 0 NOT NULL,
    daily_reset date DEFAULT CURRENT_DATE NOT NULL,
    compute_budget_micros bigint DEFAULT 0 NOT NULL,
    compute_used_micros bigint DEFAULT 0 NOT NULL,
    daily_used_micros bigint DEFAULT 0 NOT NULL,
    daily_limit_micros bigint DEFAULT 0 NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    unmetered boolean DEFAULT false NOT NULL,
    paid_until timestamp with time zone,
    budget_reset timestamp with time zone,
    monthly_budget_micros bigint DEFAULT 0 NOT NULL,
    storage_used_bytes bigint DEFAULT 0 NOT NULL,
    storage_extra_bytes bigint DEFAULT 0 NOT NULL,
    storage_checked_at timestamp with time zone,
    pending_tier text,
    pending_storage_bytes bigint,
    totp_secret text,
    totp_enabled boolean DEFAULT false NOT NULL,
    recovery_codes text[] DEFAULT '{}'::text[] NOT NULL,
    memory_enabled boolean DEFAULT true NOT NULL,
    memory_extracted_at timestamp with time zone,
    enc_dek bytea,
    dek_salt bytea
);


ALTER TABLE public.users OWNER TO darkai;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: darkai
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.users_id_seq OWNER TO darkai;

--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: darkai
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: api_tokens id; Type: DEFAULT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.api_tokens ALTER COLUMN id SET DEFAULT nextval('public.api_tokens_id_seq'::regclass);


--
-- Name: hosts id; Type: DEFAULT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.hosts ALTER COLUMN id SET DEFAULT nextval('public.hosts_id_seq'::regclass);


--
-- Name: payments id; Type: DEFAULT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.payments ALTER COLUMN id SET DEFAULT nextval('public.payments_id_seq'::regclass);


--
-- Name: usage_logs id; Type: DEFAULT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.usage_logs ALTER COLUMN id SET DEFAULT nextval('public.usage_logs_id_seq'::regclass);


--
-- Name: user_memory id; Type: DEFAULT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.user_memory ALTER COLUMN id SET DEFAULT nextval('public.user_memory_id_seq'::regclass);


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Name: api_tokens api_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.api_tokens
    ADD CONSTRAINT api_tokens_pkey PRIMARY KEY (id);


--
-- Name: api_tokens api_tokens_token_key; Type: CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.api_tokens
    ADD CONSTRAINT api_tokens_token_key UNIQUE (token);


--
-- Name: containers containers_host_id_browser_port_key; Type: CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.containers
    ADD CONSTRAINT containers_host_id_browser_port_key UNIQUE (host_id, browser_port);


--
-- Name: containers containers_host_id_container_name_key; Type: CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.containers
    ADD CONSTRAINT containers_host_id_container_name_key UNIQUE (host_id, container_name);


--
-- Name: containers containers_host_id_port_key; Type: CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.containers
    ADD CONSTRAINT containers_host_id_port_key UNIQUE (host_id, port);


--
-- Name: containers containers_pkey; Type: CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.containers
    ADD CONSTRAINT containers_pkey PRIMARY KEY (user_id);


--
-- Name: goose_db_version goose_db_version_pkey; Type: CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.goose_db_version
    ADD CONSTRAINT goose_db_version_pkey PRIMARY KEY (id);


--
-- Name: hosts hosts_name_key; Type: CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.hosts
    ADD CONSTRAINT hosts_name_key UNIQUE (name);


--
-- Name: hosts hosts_pkey; Type: CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.hosts
    ADD CONSTRAINT hosts_pkey PRIMARY KEY (id);


--
-- Name: oauth_identities oauth_identities_pkey; Type: CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.oauth_identities
    ADD CONSTRAINT oauth_identities_pkey PRIMARY KEY (provider, provider_uid);


--
-- Name: oauth_state oauth_state_pkey; Type: CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.oauth_state
    ADD CONSTRAINT oauth_state_pkey PRIMARY KEY (state);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: session_episodes session_episodes_pkey; Type: CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.session_episodes
    ADD CONSTRAINT session_episodes_pkey PRIMARY KEY (user_id, session_id);


--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (token);


--
-- Name: tier_defaults tier_defaults_pkey; Type: CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.tier_defaults
    ADD CONSTRAINT tier_defaults_pkey PRIMARY KEY (tier);


--
-- Name: totp_pending totp_pending_pkey; Type: CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.totp_pending
    ADD CONSTRAINT totp_pending_pkey PRIMARY KEY (token);


--
-- Name: usage_logs usage_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.usage_logs
    ADD CONSTRAINT usage_logs_pkey PRIMARY KEY (id);


--
-- Name: user_memory user_memory_pkey; Type: CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.user_memory
    ADD CONSTRAINT user_memory_pkey PRIMARY KEY (id);


--
-- Name: users users_api_token_key; Type: CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_api_token_key UNIQUE (api_token);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: idx_api_tokens_token; Type: INDEX; Schema: public; Owner: darkai
--

CREATE INDEX idx_api_tokens_token ON public.api_tokens USING btree (token) WHERE (revoked = false);


--
-- Name: idx_api_tokens_user; Type: INDEX; Schema: public; Owner: darkai
--

CREATE INDEX idx_api_tokens_user ON public.api_tokens USING btree (user_id);


--
-- Name: idx_containers_host; Type: INDEX; Schema: public; Owner: darkai
--

CREATE INDEX idx_containers_host ON public.containers USING btree (host_id);


--
-- Name: idx_containers_last_active; Type: INDEX; Schema: public; Owner: darkai
--

CREATE INDEX idx_containers_last_active ON public.containers USING btree (last_active);


--
-- Name: idx_containers_status; Type: INDEX; Schema: public; Owner: darkai
--

CREATE INDEX idx_containers_status ON public.containers USING btree (status);


--
-- Name: idx_oauth_state_expires; Type: INDEX; Schema: public; Owner: darkai
--

CREATE INDEX idx_oauth_state_expires ON public.oauth_state USING btree (expires_at);


--
-- Name: idx_oauth_user; Type: INDEX; Schema: public; Owner: darkai
--

CREATE INDEX idx_oauth_user ON public.oauth_identities USING btree (user_id);


--
-- Name: idx_session_episodes_user; Type: INDEX; Schema: public; Owner: darkai
--

CREATE INDEX idx_session_episodes_user ON public.session_episodes USING btree (user_id);


--
-- Name: idx_sessions_expires; Type: INDEX; Schema: public; Owner: darkai
--

CREATE INDEX idx_sessions_expires ON public.sessions USING btree (expires_at);


--
-- Name: idx_sessions_user; Type: INDEX; Schema: public; Owner: darkai
--

CREATE INDEX idx_sessions_user ON public.sessions USING btree (user_id);


--
-- Name: idx_totp_pending_expires; Type: INDEX; Schema: public; Owner: darkai
--

CREATE INDEX idx_totp_pending_expires ON public.totp_pending USING btree (expires_at);


--
-- Name: idx_usage_logs_created_at; Type: INDEX; Schema: public; Owner: darkai
--

CREATE INDEX idx_usage_logs_created_at ON public.usage_logs USING btree (created_at);


--
-- Name: idx_usage_logs_user_id; Type: INDEX; Schema: public; Owner: darkai
--

CREATE INDEX idx_usage_logs_user_id ON public.usage_logs USING btree (user_id);


--
-- Name: idx_user_memory_embedding; Type: INDEX; Schema: public; Owner: darkai
--

CREATE INDEX idx_user_memory_embedding ON public.user_memory USING ivfflat (embedding public.vector_cosine_ops) WITH (lists='100');


--
-- Name: idx_user_memory_live; Type: INDEX; Schema: public; Owner: darkai
--

CREATE INDEX idx_user_memory_live ON public.user_memory USING btree (user_id) WHERE (superseded_by IS NULL);


--
-- Name: idx_user_memory_type; Type: INDEX; Schema: public; Owner: darkai
--

CREATE INDEX idx_user_memory_type ON public.user_memory USING btree (user_id, mem_type) WHERE (superseded_by IS NULL);


--
-- Name: idx_users_api_token; Type: INDEX; Schema: public; Owner: darkai
--

CREATE INDEX idx_users_api_token ON public.users USING btree (api_token);


--
-- Name: payments_provider_pid_uniq; Type: INDEX; Schema: public; Owner: darkai
--

CREATE UNIQUE INDEX payments_provider_pid_uniq ON public.payments USING btree (provider, provider_pid) WHERE (provider_pid IS NOT NULL);


--
-- Name: payments_user_idx; Type: INDEX; Schema: public; Owner: darkai
--

CREATE INDEX payments_user_idx ON public.payments USING btree (user_id);


--
-- Name: api_tokens api_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.api_tokens
    ADD CONSTRAINT api_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: containers containers_host_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.containers
    ADD CONSTRAINT containers_host_id_fkey FOREIGN KEY (host_id) REFERENCES public.hosts(id);


--
-- Name: containers containers_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.containers
    ADD CONSTRAINT containers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: oauth_identities oauth_identities_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.oauth_identities
    ADD CONSTRAINT oauth_identities_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: payments payments_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: session_episodes session_episodes_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.session_episodes
    ADD CONSTRAINT session_episodes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: sessions sessions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: totp_pending totp_pending_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.totp_pending
    ADD CONSTRAINT totp_pending_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: usage_logs usage_logs_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.usage_logs
    ADD CONSTRAINT usage_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: user_memory user_memory_superseded_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.user_memory
    ADD CONSTRAINT user_memory_superseded_by_fkey FOREIGN KEY (superseded_by) REFERENCES public.user_memory(id) ON DELETE SET NULL;


--
-- Name: user_memory user_memory_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: darkai
--

ALTER TABLE ONLY public.user_memory
    ADD CONSTRAINT user_memory_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict 2WPWajyQyYcD4VajFESe03TbLodHGfLMwoshF7qboBWQnFL0ts3QLKkAcjDTwUB

